language: java

jdk:
  - oraclejdk15
  - openjdk15

stages:
    - name: build
    - name: snapshot
      if: branch = master
    - name: release
      if: branch = release

jobs:
  include:
    - stage: build
      script: ./gradlew -x test build
    - stage: snapshot
      script: ./gradlew publish -Dsnapshot=true
    - stage: release
      script: ./gradlew publish